[build]
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/indexswapy/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/indexswapy/:splat"
  status = 200 